CodeForPhilly/balancer-main

frontend/package-lock.json, frontend/src/pages/PatientManager/NewPatientForm.tsx
Replaced radio button instead of checkboxes for the two option Kat mentioned.
=> Radio buttons added instead of checkboxes

frontend/src/components/Header/Chat.tsx, frontend/src/components/Header/ConversationList.tsx, frontend/src/components/Header/chat.css
Closes #178 
1. Truncate conversation title and create tooltip for full title on mouse hover
2. Dynamic resizing for all screen sizes. Wide:
Small: 
3. Fix hidden scroll bar 
4. Change suggestion prompt layout from horizontal to vertical for wide and medium screen sizes 
5. Increase width of text input when editing the conversation title
=> 178 chat UI improvements

frontend/src/components/Footer/Footer.tsx
Fix for #126 
- Clicking Enter in the input box for emails now will "submit" them
- Submitting something will now log the email address, and clear out the input field (there's a TODO on it, to send the info to a mailing list when that's available)
- setIsPressed functionality was migrated over to the new onClick function 
- I also removed the mouseUp/mouseDown functions as they were interacting with the onClick event.
=> Enter submits e-mails to mailing list

frontend/src/components/Header/LoginMenuDropDown.tsx, frontend/src/utils/classNames.ts
Enhance the login page's responsiveness by improving the layout and styling for better user experience across different devices. Introduce a utility function for class name management to streamline conditional class assignments.
=> Fix responsive version for login page

server/api/views/listMeds/serializers.py, server/api/views/listMeds/urls.py, server/api/views/listMeds/views.py
=> created endpoint to insert medication

frontend/src/api/apiClient.ts, frontend/src/pages/PatientManager/NewPatientForm.tsx
@taichan03 
fixes the 401 unauthorized when trying to submit medical recommendation.
=> fix: :bug: 401 on /v1/api/get_med_recommend

frontend/src/components/ErrorMessage.tsx, frontend/src/components/Header/Chat.tsx, server/api/views/conversations/serializers.py, server/api/views/conversations/views.py
- Fixes auto scroll when submitting a message to the chatbot. The chat will now scroll the the bottom after the user submits a message
- Improve error message description details as requested in #127 . I noticed this bug when I didn't supply an API key- now it can give more descriptive error messages instead of a general 500 error.
- Improve error tracking/logging on the backend when it is caused by an OpenAI API error
- Fix bug where messages were not displayed in the correct order. The frontend will now sort the messages by time stamp
- Small UI changes to have the chat title bar outside of the scrollable area 
- Removal of `dangerouslySetInnerHTML` from chat component
=> Chat improvements and bug fixes- auto scroll, message timestamping, and UI tweaks

frontend/src/pages/DrugSummary/DrugSummaryForm.tsx
This PR adds dynamic resizing to the chatbox input per https://github.com/CodeForPhilly/balancer-main/issues/180
I modified the code by prompting GPT-4o and saved the prompt  in the commit message 
The changes add a state variable for the input box height  and a handler to update it in the React functional component 
I tested the changes by running `docker compose up --build` and navigating to `http://localhost:3000/drugsummary`
=> [#180] Add dynamic resizing to the chatbot input box

README.md
This PR updates the README per https://github.com/CodeForPhilly/balancer-main/issues/215
=> [#215] Dev. Issue: Update README with Contributing guidelines

frontend/src/pages/ListMeds/ListMeds.tsx, frontend/src/pages/PatientManager/NewPatientForm.tsx, frontend/src/pages/PatientManager/PatientManager.tsx, frontend/src/pages/PatientManager/PatientSummary.tsx, frontend/src/pages/PatientManager/PatientTypes.ts
I feel is not perfect yet, but it does edit the form fields. please feel free to try this branch before merging @taichan03 . Also, if the editing flow doesn't match what you were looking for hit me up. @katjost
=> feat: ✨ add edit patient form functionality

frontend/src/components/Table/Table.tsx, frontend/src/pages/Files/ListOfFiles.tsx, frontend/src/pages/Help/DataSources.tsx
=> Widen sources table and make corners round.

frontend/src/pages/About/About.tsx
=> removed donations text and button

evaluation/evals.py, server/api/views/text_extraction/views.py
This PR adds med rule extraction tests and model evaluations as  part of #262
=> [WIP] [#262] Add med rule extraction tests and model evaluations

frontend/src/pages/PatientManager/PatientHistory.tsx
List of Patients Mobile UI updated
=> 244 identify areas of mobile that need to be fixed

server/api/views/text_extraction/urls.py, server/api/views/text_extraction/views.py
This PR removes the unused TextExtractionAPIView per https://github.com/CodeForPhilly/balancer-main/issues/278
=> [#278] Remove dead TextExtractionAPIView

frontend/src/App.css, frontend/src/components/Modal/Modal.tsx, frontend/src/pages/Feedback/FeedbackForm.tsx, frontend/src/pages/PatientManager/NewPatientForm.tsx, frontend/src/pages/PatientManager/PatientSummary.tsx
Added mobile drop down kebab menu item, with times icon, along with some other minor adjustments for consistency.
=> Added mobile drop down

frontend/src/components/Header/Header.tsx, frontend/src/components/Header/MdNavBar.tsx
Logo was not functioning, MdNavBar needed access to handleForm function in the Header.
=> Added handleForm to MdNavBar so Balancer logo triggers the function

frontend/src/components/Header/Chat.tsx, frontend/src/components/Header/chat.css, frontend/tailwind.config.js
=> feat: #359 - Add animation to chat button

frontend/src/pages/PatientManager/PatientSummary.tsx
=> feat: #340 - Display explanatory text when there are no options for each tier

frontend/src/pages/PatientManager/NewPatientForm.tsx, frontend/src/pages/PatientManager/PatientManager.tsx
=> bugfix: #347 - Add any_pregnancy to clear form logic

frontend/src/pages/Files/FileRow.tsx, frontend/src/pages/Files/ListOfFiles.tsx
=> bugfix: #319 - Fix yesterday's date issue for publication date

frontend/src/pages/About/About.tsx
=> feat: #357 - Add mission section to about page
